#!/bin/zsh

if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|revert|perf)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid." >&2
    exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,72}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi
