[versions]
build-tools-version = "34.0.0"
sdk-compile-version = "34"
sdk-target-version = "34"
sdk-min-version = "23"

android-gradleplugin-version = "8.6.1"

androidx-compose-material-version = "1.7.2"
androidx-compose-ui-version = "1.7.2"
androidx-navigation-version = "2.8.1"

dokka-version = "1.9.20"

google-dagger-version = "2.52"

jacoco-version = "0.8.12"

kotlin-compiler-version = "1.3.2"
kotlin-version = "2.0.20"

[libraries]
android-gradleplugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradleplugin-version" }

androidx-annotation = "androidx.annotation:annotation:1.8.2"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.9.2"
androidx-compose-animation = "androidx.compose.animation:animation:1.7.2"
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose-material-version" }
androidx-compose-materialiconsextended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose-material-version" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui-version" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui-version" }
androidx-compose-ui-toolingpreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui-version" }
androidx-corektx = "androidx.core:core-ktx:1.13.1"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.1.1"
androidx-lifecycle-viewmodelcompose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.8.6"
androidx-hilt-navigationcompose = "androidx.hilt:hilt-navigation-compose:1.2.0"
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-version" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "androidx-navigation-version" }
androidx-navitation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "androidx-navigation-version" }

jetbrains-dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka-version" }
jetbrains-kotlin-gradleplugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-version" }
jetbrains-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-version" }
jetbrains-kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0"

google-dagger-android = { module = "com.google.dagger:dagger", version.ref ="google-dagger-version" }
google-dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref ="google-dagger-version" }
google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref ="google-dagger-version" }
google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref ="google-dagger-version" }

google-android-material = "com.google.android.material:material:1.12.0"

isupatches-wisefy-bom = "com.isupatches.android.wisefy:wisefy-bom:5.0.0-RC3"
isupatches-wisefy-accesspoints = { module = "com.isupatches.android.wisefy:accesspoints" }
isupatches-wisefy-addnetwork = { module = "com.isupatches.android.wisefy:addnetwork" }
isupatches-wisefy-core = { module = "com.isupatches.android.wisefy:core" }
isupatches-wisefy-ktx = { module = "com.isupatches.android.wisefy:ktx" }
isupatches-wisefy-networkinfo = { module = "com.isupatches.android.wisefy:networkinfo" }
isupatches-wisefy-networkconnection = { module = "com.isupatches.android.wisefy:networkconnection" }
isupatches-wisefy-removenetwork = { module = "com.isupatches.android.wisefy:removenetwork" }
isupatches-wisefy-savednetworks = { module = "com.isupatches.android.wisefy:savednetworks" }
isupatches-wisefy-signal = { module = "com.isupatches.android.wisefy:signal" }
isupatches-wisefy-wifi = { module = "com.isupatches.android.wisefy:wifi" }
isupatches-wisefy-wisefy = { module = "com.isupatches.android.wisefy:wisefy" }

[bundles]
androidx-compose-ui = ['androidx-compose-ui', 'androidx-compose-ui-tooling', 'androidx-compose-ui-toolingpreview']
androidx-compose-material = ['androidx-compose-material', 'androidx-compose-materialiconsextended']
androidx-navigation = ['androidx-navigation-compose', 'androidx-navigation-fragment', 'androidx-navitation-ui']

google-dagger = ["google-dagger-android", "google-dagger-hilt-android"]
google-dagger-compiler = ["google-dagger-compiler", "google-dagger-hilt-compiler"]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradleplugin-version" }
android-library = { id = "com.android.library", version.ref = "android-gradleplugin-version" }

google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "google-dagger-version"}
google-ksp = { id = "com.google.devtools.ksp", version = "2.0.20-1.0.25" }

java-platform = { id = "java-platform" }

jetbrains-kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-version" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka-version" }

cpd = { id = "de.aaschmid.cpd", version = "3.4" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.7" }
dexcount = { id = "com.getkeepsafe.dexcount", version = "4.0.0" }
kotlinter = { id = "org.jmailen.kotlinter", version = "4.4.1" }

wisefy-android-library = { id = "wisefy-android-library" }
wisefy-android-publish = { id = "wisefy-android-publish" }
wisefy-android-bom-publish = { id = "wisefy-android-bom-publish" }
