[versions]
androidx-espresso-version = "3.5.1"
mockito-version = "5.12.0"

[libraries]
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso-version" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-espresso-version" }
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-rules = "androidx.test:rules:1.5.0"

junit = "junit:junit:4.13.2"

kotlin-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.1"

mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito-version" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-version" }

[bundles]

[plugins]
