name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["TODO", "Enhancement", "From User", "Requires Discussion", "Status - Not Started"]
assignees:
  - isuPatches
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating an issue to improve this library! Please check [the current issues](https://github.com/isuPatches/android-wisefy/issues) to make sure that the improvement isn't already being worked on.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: description
    attributes:
      label: Description
      description: Please describe the feature request with a high level overview. These could be user stories as well like 'As a developer I want ___ so that  ___'
    validations:
      required:
        true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "Describe in more detail the request.  (f.e. - a method is added to the library, - the method when called does ___, etc.)"
      value: |
        - 
        -
        -
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please add any additional insight or use-cases for context.
  - type: markdown
    attributes:
      value: |
        Images are also welcome.  Please attach them to the explanation for the feature request.
